version: '3.0'

services:
  react-app:
    image: react-app
    build:
      context: ./client
    stdin_open: true
    env_file:
      - ./client/.production.env
    ports:
      - 80:3000
    command: npm run start
    restart: always
    networks:
      - pern-app
  node-api:
    image: node-api
    build:
      context: ./server
    ports:
      - 7000:7000
    env_file:
      - ./server/.production.env
    depends_on:
      - postgres
    command: npm run start
    restart: always
    networks:
      - pern-app
  postgres:
    container_name: postgres
    image: postgres:12
    env_file:
      - ./server/.production.env
    environment:
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata-new:/var/lib/postgresql/data
    restart: always
    networks:
      - pern-app
networks:
  pern-app:
    driver: bridge
volumes: 
  pgdata-new:
    driver: local
  
